Documentation
Knox-AAU/FunctionalityLayer_FactChecker pull request #20
Opened 2021-12-07 17:57 UTC by FreddyB0y

Added documentation for nearly every class and method

2021-12-07 18:21 UTC, ESMA3000 requested changes
Den ene kommentar er det eneste der skal rettes. Ellers er det fint. gw

2021-12-07 18:21 UTC, ESMA3000 commented on FactChecker/WordcountDB/Article.cs
> +        /// <returns>List of articles with ID's mathing the parameter <paramref name="id"/></returns>
Den returner kun en article, da alle artikler har et unikt id

2021-12-07 18:32 UTC, FreddyB0y commented on FactChecker/WordcountDB/Article.cs
> +        /// <returns>List of articles with ID's mathing the parameter <paramref name="id"/></returns>
Fixed!

2021-12-13 12:08 UTC, ESMA3000 approved these changes

2022-09-09 11:11 UTC, BlankWheein approved these changes

2022-09-09 11:38 UTC, merged