Rake implementation
Knox-AAU/FunctionalityLayer_FactChecker pull request #37
Opened 2022-09-29 10:42 UTC by GrimmFantasy

2022-09-29 13:25 UTC, D-Kuma-C approved these changes
k

2022-09-29 13:33 UTC, BlankWheein requested changes

2022-09-29 13:33 UTC, BlankWheein commented on FactChecker/Intefaces/IFactChecking.cs
> +        public static int ID = 0;
det skal ikke være static

2022-09-30 07:16 UTC, BlankWheein approved these changes

2022-09-30 07:16 UTC, merged